# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

SoftwareS3:
    resource: "@QuindimotosProyectoBundle/Resources/config/routing.yml"
    prefix:   
    
SoftwareS31:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix:   /alimentos
    

    
_user_bundle:
     resource: "@QuindimotosProyectoBundle/Resources/config/routing.yml"