# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    role_hierarchy:
       
        ROLE_SECRETARIA:  ROLE_SECRETARIA
        ROLE_TECNICO:     ROLE_TECNICO
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]         

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /QM
                provider: fos_userbundle
            logout:
                path:   /logout
                target: /login
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/QM, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/QM, role: [ROLE_SECRETARIA, ROLE_TECNICO, ROLE_ADMIN] }
        
        #- { path: ^/admin/, role: ROLE_ADMIN }

