Inventariomoto:
    type: entity
    table: inventariomoto
    fields:
        id:
            id: true
            type: string
            length: 20
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        espejos:
            type: string
            length: 20
            fixed: false
            nullable: false
        direccionales:
            type: string
            length: 20
            fixed: false
            nullable: false
        tapaslaterales:
            type: string
            length: 20
            fixed: false
            nullable: false
        sillin:
            type: string
            length: 20
            fixed: false
            nullable: false
        tabacos:
            type: string
            length: 20
            fixed: false
            nullable: false
        stop:
            type: string
            length: 20
            fixed: false
            nullable: false
        gatos:
            type: string
            length: 20
            fixed: false
            nullable: false
        reflectivas:
            type: string
            length: 20
            fixed: false
            nullable: false
        tapatanqueaceite:
            type: string
            length: 20
            fixed: false
            nullable: false
        emblemas:
            type: string
            length: 20
            fixed: false
            nullable: false
        parrillas:
            type: string
            length: 20
            fixed: false
            nullable: false
        luzdelantera:
            type: string
            length: 20
            fixed: false
            nullable: false
        pito:
            type: string
            length: 20
            fixed: false
            nullable: false
        bateria:
            type: string
            length: 20
            fixed: false
            nullable: false
        velocimetro:
            type: string
            length: 20
            fixed: false
            nullable: false
        guardafango:
            type: string
            length: 20
            fixed: false
            nullable: false
        juegodeherramientas:
            type: string
            length: 20
            fixed: false
            nullable: false
        llaves:
            type: string
            length: 20
            fixed: false
            nullable: false
        tanque:
            type: string
            length: 20
            fixed: false
            nullable: false
        manual:
            type: string
            length: 20
            fixed: false
            nullable: false
        llantas:
            type: string
            length: 20
            fixed: false
            nullable: false
    manyToOne:
        moto:
            targetEntity: Moto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Moto_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
