SecurityRoles:
    type: entity
    table: security_roles
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        role:
            type: string
            length: 70
            fixed: false
            nullable: false
    manyToMany:
        user:
            targetEntity: SecurityUsers
            cascade: {  }
            mappedBy: role
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
