<?php

namespace Quindimotos\ProyectoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class NavegationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Quindimotos\ProyectoBundle\Controller\NavegationController();
        return $instance;
    }
}
