S31_homepage:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Default:index }
 
JAMAB_listar:
      pattern:  /listar
      defaults: { _controller: AcmeDemoBundle:Default:listar }

JAMAB_insertar:
      pattern:  /insertar
      defaults: { _controller: AcmeDemoBundle:Default:insertar }
JAMAB_buscar:
      pattern:  /buscar
      defaults: { _controller: AcmeDemoBundle:Default:buscarPorNombre }

JAMAB_ver:
      pattern:  /ver
      defaults: { _controller: AcmeDemoBundle:Default:ver }    
