S3_homepage:
    pattern:  /QM
    defaults: { _controller: QuindimotosProyectoBundle:Default:index }
    

#proyecto
# final del archivo:
Annotations:
    resource: "@QuindimotosProyectoBundle/Controller/"
    prefix:   /
    type:     annotation
QUINDI_RegistarSolicitud:
    pattern: /regisSol
    defaults: { _controller: QuindimotosProyectoBundle:Navegation:registarSolicitud }
QUINDI_tecnicosDisponibles:
    pattern: /tec_Dis
    defaults: { _controller: QuindimotosProyectoBundle:Navegation:tecnicosDisponibles }
QUINDI_regAndN:
    pattern: /regAndN
    defaults: { _controller: QuindimotosProyectoBundle:Navegation:regisAndNotify }
QUINDI_regUser:
    pattern: /regUser
    defaults: { _controller: QuindimotosProyectoBundle:Navegation:registarUsuariosSistema }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile